name: funds
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Infra
      fonts:
        - asset: fonts/InfraBlack.otf
          weight: 900
        - asset: fonts/InfraBlackItalic.otf
          weight: 900
          style: italic
        - asset: fonts/InfraExtraBold.otf
          weight: 800
        - asset: fonts/InfraExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: fonts/InfraBold.otf
          weight: 700
        - asset: fonts/InfraBoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/InfraSemiBold.otf
          weight: 600
        - asset: fonts/InfraSemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/InfraMedium.otf
          weight: 500
        - asset: fonts/InfraMediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/InfraRegular.otf
          weight: 400
        - asset: fonts/InfraRegularItalic.otf
          weight: 400
          style: italic
        - asset: fonts/InfraLight.otf
          weight: 300
        - asset: fonts/InfraLightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/InfraExtraLight.otf
          weight: 200
        - asset: fonts/InfraExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/InfraThin.otf
          weight: 100
        - asset: fonts/InfraThinItalic.otf
          weight: 100
          style: italic
